# Generated by Django 5.0.6 on 2024-05-29 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.AddField(
            model_name='store',
            name='X',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Y',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_line',
            field=models.CharField(default='Ho Chi Minh City', max_length=255),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255)),
                ('X', models.CharField(max_length=10, null=True)),
                ('Y', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StoreAddress',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
