# Generated by Django 5.0.6 on 2024-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0003_alter_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='X',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Y',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AlterField(
            model_name='store',
            name='X',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='Y',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(null=True, to='foodstore.category'),
        ),
    ]
