# Generated by Django 5.0.6 on 2024-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0004_food_discount_alter_address_x_alter_address_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
