# Generated by Django 5.0.6 on 2024-06-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0005_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
