# Generated by Django 5.0.6 on 2024-06-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0008_alter_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item_topping',
            name='unit_price_at_order',
            field=models.IntegerField(null=True),
        ),
    ]
