# Generated by Django 5.0.6 on 2024-06-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0009_order_item_topping_unit_price_at_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item_topping',
            old_name='toppings',
            new_name='topping',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='foods',
            new_name='food',
        ),
    ]
