# Generated by Django 5.0.6 on 2024-06-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0011_alter_order_user_alter_orderitem_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_fee',
            new_name='total',
        ),
    ]
