# Generated by Django 5.0.6 on 2024-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0012_rename_shipping_fee_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(null=True),
        ),
    ]
