# Generated by Django 5.0.6 on 2024-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
